sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t nikhilknick/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nikhilknick/react-test npm run test

after_success:
  - docker build -t nikhilknick/multi-client -f ./client
  - docker build -t nikhilknick/multi-nginx -f ./nginx
  - docker build -t nikhilknick/multi-server -f ./server
  - docker build -t nikhilknick/multi-worker -f ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push nikhilknick/multi-client
  - docker push nikhilknick/multi-nginx
  - docker push nikhilknick/multi-server
  - docker push nikhilknick/multi-worker
